### ISSUE TITLE
岩手県データで404

### ISSUE THREAD

**Issue by inoue-katsumi** [madefor/postal-code-api#3]
素敵なパッケージをありがとうございます。

以下３つが 404 エラーになっています。

https://madefor.github.io/postal-code-api/api/v1/029/5512.json
https://madefor.github.io/postal-code-api/api/v1/029/5514.json
https://madefor.github.io/postal-code-api/api/v1/029/5505.json

**Comment by miya0001** [comment]
報告ありがとうございます！

**Comment by inoue-katsumi** [comment]
ありがとうございます。今日は再現しませんでした。
